language: java

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

install: true

jobs:
  include:
  - stage: static-analysis
    script: mvn -B checkstyle:check
    name: "Checkstyle"

  - stage: test
    script: mvn -B test
    name: "JUnit"

stages:
  - static-analysis
  - test
